### PR TITLE
2022 update everything, django to 4.1

### PR DESCRIPTION
**Pull request by tswfi**
* python 3.10
* Django 4.1
  * change all the deprecated stuff
* bootstrap files
* all dependencies
* remove `django-user-language-middleware` and use our own implementation
* add black to tox
* change tox4 back to tox
* run black on everything (except migrations)
* add `pyproject.toml` to configure black

And I probably already forgot something that was updated...

### CODE REVIEW

**Comment by tswfi** [comment]
This will obsolete #360 and #358

**Comment by olmari** [comment]
As current stable Debian 11 sports Python 3.9.2, this doesn't pass checks, and there is no backports for later Python at this time.

```
mulysa@bravo:~/mulysa$ pipenv update
Warning: Your Pipfile requires python_version 3.10, but you are using 3.9.2 (/opt/mulysa/.local/share/v/m/bin/python).
  $ pipenv check will surely fail.

mulysa@bravo:~/mulysa$ pipenv check
Checking PEP 508 requirements…
Specifier python_version does not match 3.10 (3.9).
Failed!
```

**Comment by tswfi** [comment]
And now also obsoletes #366

**Review by olmari — CHANGES_REQUESTED** [review]
OIDC (django-oauth-toolkit) needs some reworking as it has new major breaking version, https://github.com/TampereHacklab/mulysa/issues/365

Everything else seems to work fine, tried to test every aspect I can figure out and no breakages seen.

**Comment by olmari** [comment]
I'm not sure did I miss this one earlier or is it totally new, but on latest update there is such warning

```
mulysa@bravo:~/mulysa$ pipenv run ./manage.py migrate
System check identified some issues:

WARNINGS:
?: (2_0.W001) Your URL pattern 'account-confirm-email/(?P<key>[-:\w]+)/' [name='account_confirm_email'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().
```

**Review by olmari — APPROVED** [review]
That warning apparently comes from django-oauth-toolkit so it'll be fixe upstream at some time.

Latest code made OIDC to work instantly with already set settings, so now (OIDC) instructions works as-is, PR good to go.

**Pull request merged**
