### PR TITLE
Document skip authorization bit, fixes #335

### LINKED ISSUE #335: SSO login flow: extraneous accept step
When logging in to any service where Mulysa acts as OIDC-provider, after successful credentials entered, there comes always this page, which is very extraneous in Mulysa provided SSO-login. Lets figure if there is config option or other way to not have this question at all:

image

### PR DESCRIPTION
**Pull request by tswfi**

### CODE REVIEW

**Comment by olmari** [comment]
Well, this caters the explanation of "skip checks", bigger or biggest issue is that option itself is nowhere to be seen on the /o/applications settings, but only in django-admin.

**Review by olmari — CHANGES_REQUESTED** [review]
As "fact" this is very good, I feel there should be added mention that this fonuds from django-admin side and not on `o/applications/` directly like rest of it.

**Comment by tswfi** [comment]
hmm, true. I forgot about the `o/applications` view

**Comment by tswfi** [comment]
nope, this is not the way

**Pull request closed without merging**
